services:
  transport-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-transport-api
    ports:
      - "8888:8888"
    environment:
      APP_HOST: "127.0.0.1"
      APP_PORT: "8080"
      APP_DATABASE_PATH: "/data/transport.db"
      APP_JWT_SECRET: "very-secret-key"
    volumes:
      - transport_data:/data

volumes:
  transport_data:
